### ISSUE TITLE
usegb4e causes errors

### ISSUE THREAD

**Issue by drewx0r** [andrasbarany/cascadilla-xelatex-biblatex#1]
when I use the usegb4e option, the compile errors out (runs up against a capacity limit). Wrapping the \RequirePackage{gb4e} line 165 of the class file in \AtBeginDocument{} fixes the issue (gb4e always causes me problems when I load it anywhere but last), but I'm not sure if it messes up the desired spacing. The spacing is different if you wrap just line 165 vs. wrapping the whole block (lines 165-187). I can't tell if either of those match up with the spacing that comes out when using expex.

**Comment by andrasbarany** [comment]
Thanks for for the comment @drewx0r. Does removing 

```
\usepackage{listings}
\usepackage{xcolor}
``` 

help? I'm loading those in the example file and they seem to give rise to the problem with `gb4e`.
